/**
 * Reading branch names out of merge-commit subjects.
 *
 * Pushes to main here mostly do not go through a pull request — the builder
 * merges locally and pushes the branch — so the PR API knows nothing about them.
 * The merge commit itself is the only record, and its subject is generated by
 * git in a fixed shape. Pure and dependency-free so the parsing is unit-tested
 * without a network or a cache.
 */

/** Just the first line; git puts the branch names there and details below. */
function firstLine(message: string): string {
  return message.split("\n", 1)[0]?.trim() ?? "";
}

// Matches releases_merge_subject_len (0085). A subject longer than this is a
// commit body someone wrote without a blank line, not a subject.
const MAX_SUBJECT = 300;

/**
 * The one-line name of a push, stored on the release it produced (0085).
 *
 * This is what the Shipped timeline shows, so it stands in for "what was this
 * merge" long after the commit itself is unreachable. Null for an empty message
 * rather than an empty string, since the column's check constraint rejects one.
 */
export function mergeSubject(message: string): string | null {
  const subject = firstLine(message);
  if (!subject) return null;
  return subject.length > MAX_SUBJECT ? subject.slice(0, MAX_SUBJECT) : subject;
}

/**
 * The branch a merge commit brought IN, for labeling the release it produced.
 *
 *   "Merge branch 'dev'"                              → dev
 *   "Merge branch 'dev' into main"                    → dev
 *   "Merge remote-tracking branch 'origin/main' …"    → origin/main
 *   "Merge pull request #12 from Jynx-hub/dev"        → dev
 *   "fix(email): stop copying the firm inbox"         → null
 */
export function parseMergedBranch(message: string): string | null {
  const subject = firstLine(message);

  const pr = subject.match(/^Merge pull request #\d+ from [^/\s]+\/(.+)$/);
  if (pr) return pr[1].trim() || null;

  // "remote-tracking branch" is the same event with a longer noun, and
  // parseMergeTarget below already reads both — a reader that accepted only one
  // of them reported "no branch merged" for a commit that plainly merged one.
  const branch = subject.match(/^Merge (?:remote-tracking )?branch '([^']+)'/);
  if (branch) return branch[1].trim() || null;

  return null;
}

/**
 * The branch a merge commit was merged INTO — the integration branch.
 *
 * `main`'s history carries the merge commits made on the branch that feeds it,
 * so subjects like "Merge branch 'AgentPDF' into dev" are how we learn `dev`
 * exists and is where work lands before a release. Returns null for a merge with
 * no explicit target (git omits "into X" when merging into the current branch).
 */
export function parseMergeTarget(message: string): string | null {
  const subject = firstLine(message);
  const into = subject.match(/^Merge (?:branch|remote-tracking branch) '[^']+' into (.+)$/);
  return into ? into[1].trim() || null : null;
}

/**
 * Distinct integration branches named by these commit messages, most recent
 * first, excluding the default branch itself. Capped so the caller can't fan
 * out into one GitHub request per branch.
 */
export function pickIntegrationBranches(
  messages: string[],
  defaultBranch: string,
  limit: number
): string[] {
  const branches: string[] = [];
  for (const message of messages) {
    const target = parseMergeTarget(message);
    if (target === null || target === defaultBranch) continue;
    if (branches.includes(target)) continue;
    branches.push(target);
    if (branches.length >= limit) break;
  }
  return branches;
}
